version: "3"

services:
  registry:
    restart: always
    container_name: registry
    image: registry:2
    volumes:
      - ./hub:/var/lib/registry

networks:
  default:
    external:
      name: ${NETWORK_NAME}
